### PR TITLE
Fix pypi link

### PR DESCRIPTION
**Pull request by boxed**

### CODE REVIEW

**Comment by guyskk** [comment]
@boxed I read the article about mutation testing, it is interesting. But I wonder the ROI of so strict testing is pretty low for most projects, may I know the use cases of such testing?

**Comment by boxed** [comment]
Yes, the ROI can be pretty low. The idea is that you'd do it where the stakes are super high (permissions, security, that kind of thing), or where the ROI is multiplied many many times because lots of code is using the project (basic libraries used by many projects for example).

We use it in exactly these situations. The most basic the library, the more important it is that the test is super thorough. 

Another nice thing with mutation testing (at least with mutmut) is that you can do it piece meal, so I often have like a half hour left of the working day and don't want to start something big, I can just spend that time killing a few mutants because it doesn't require a lot of mental stack.

**Comment by guyskk** [comment]
Great job, good luck!

**Comment by boxed** [comment]
Thanks! And do try it on some small lib. It's a good tool to have tried a bit so when the time comes where you need it you feel comfortable pulling out this tool.

**Comment by guyskk** [comment]
Thank you! I will have a try!

**Pull request merged**
